Update 2.3

diff --git a/elog b/elog
--- a/elog
+++ b/elog
@@ -7,31 +7,38 @@
 green='\033[92m'
 yellow='\e[0;33m'
 orange='\e[38;5;166m'
+cyan='\e[0;36m'
+
+sleep 3
 
 # Default directory for eternal scanner data 
 defdir="/usr/local/share/Eternal_Scanner"
 
+# Default file that defines which program is running
+masstat="$defdir/stat"
+
+stat=$(cat $masstat | sed -n '1p')
+
+echo ""
+
 # When CTRL+C is pressed
 trap ctrl_c INT
 function ctrl_c() {
+if [ "$stat" == "1" ] 
+then
+pkill -f masscan* >/dev/null 2>&1
+rm -rf "$defdir/pid.tmp" >/dev/null 2>&1
+elif [ "$stat" == "2" ] 
+then
 kill "$PID" >/dev/null 2>&1
+rm -rf "$defdir/pid.tmp" >/dev/null 2>&1
+fi
+exit 1
 }
-echo -e "$orange" "+-------------------------+"
-echo -e "$orange" "|$green Metasploit IPS Checkout$orange |"
-echo -e "$orange" "+-------------------------+"
-echo -e "$orange" "|$yellow      Please wait       $orange |"
-echo -e "$orange" "+-------------------------+"
 
-# Timer start value to wait for msflog file generated by metasploit 
-tm="0"
-
-# variable used to check in msflog for percentage
-a=""
-
-# Read Process ID for msfconsole generated by escan
+# Read Process ID generated by escan
 PID=$(cat $defdir/pid.tmp)
 
-# Loop start
 function start(){
 
 # Define where it should be msflog file
@@ -73,14 +80,14 @@ then
 # Increase tm value + 1 from its current value
 tm=$((tm+1))
 
-# until 120s if msflog is not created then elog will exit
-if [ "$tm" == "120" ]
+# until 60s if msflog is not created then elog will exit
+if [ "$tm" == "60" ]
 then
 echo -e "$yellow" "Metasploit Not Detected"
 exit 0
 else
 
-# Timmer is not yet at 120 , pause 1 second and loop again
+# Timmer is not yet at 60 , pause 1 second and loop again
 sleep 1
 start
 fi
@@ -97,8 +104,8 @@ then
 a="$gmsft"
 sleep 1
 
-# timer value sets to 119 of 120 seconds , this way when elog ends its job it will reach 120s in 1 second and will exit itself so escan can continue its job
-tm="119"
+# timer value sets to 59 of 60 seconds , this way when elog ends its job it will reach 60s in 1 second and will exit itself so escan can continue its job
+tm="59"
 
 #start loop
 start
@@ -109,7 +116,7 @@ else
 
 echo "$gmsft"
 a="$gmsft"
-tm="119"
+tm="59"
 sleep 1
 
 # start loop
@@ -118,4 +125,105 @@ fi
 fi
 fi
 }
+
+msfc(){
+echo -e "$orange" "+---------------------------------------------------+"
+echo -e "$orange" "|$green Realtime Eternal Scan Metasploit results Checkout$orange |"
+echo -e "$orange" "+---------------------------------------------------+"
+echo -e "$orange" "|$yellow      Please wait for percentage output           $orange |"
+echo -e "$orange" "+---------------------------------------------------+"
+
+# Timer start value to wait for msflog file generated by metasploit 
+tm="0"
+
+# variable used to check in msflog for percentage
+a=""
+
+}
+
+mass() {
+# Define where it should be masscan file
+massl="$defdir/masscan"
+
+# Check if masscan pid is running
+ps --pid "$PID" &>/dev/null
+pd="$?"
+if [ "$pd" -eq "1" ]
+then
+
+if [ -f  "$massl" ] 
+then
+gmsft=$(grep "open" $massl | wc -l)
+
+if [ "$gmsft" != "$a" ]
+then 
+
+echo -ne "$yellow $gmsft$cyan Ips To Check Ahead\033[0K\r"
+exit 1
+fi
+fi
+else
+
+if [ ! -f  "$massl" ]
+then
+
+tm=$((tm+1))
+
+# until 15s if msflog is not created then elog will exit
+if [ "$tm" == "10" ]
+then
+echo -e "$yellow" "Masscan file was not found"
+rm -rf "$defdir/pid.tmp" >/dev/null 2>&1
+exit 1
+else
+
+# Timmer is not yet at 10 , pause 100 miliseconds and loop again
+sleep 1
+mass
+fi
+else
+
+# At this point msfconsole PID is running and msflog was generated to be consulted 
+
+# gmsft will grab the last value (scanned) from msflog
+gmsft=$(grep "open" $massl | wc -l)
+
+# In case gmsft is equal to variable (a) then set variable a with same value and wait 1 second
+if [ "$gmsft" == "$a" ]
+then
+a="$gmsft"
+sleep 1
+
+# timer value sets to 9 of 10 seconds , this way when elog ends its job it will reach 15s in 1 second and will exit itself so escan can continue its job
+tm="9"
+
+#start loop
+mass
+else
+
+# In case gmsft is different then variable (a) then setup a with same value
+# this process avoids repeating the same percentage on screen from msflog
+
+echo -ne "$yellow $gmsft$cyan Ips To Check Ahead\033[0K\r"
+a="$gmsft"
+tm="9"
+sleep 1
+
+# start loop
+mass
+fi
+fi
+fi
+}
+
+
+if [ "$stat" == "1" ] 
+then
+mass
+fi
+
+if [ "$stat" == "2" ] 
+then
+msfc
 start
+fi
