Update 2.2

diff --git a/escan b/escan
--- a/escan
+++ b/escan
@@ -15,18 +15,18 @@ green='\033[92m'
 red='\e[1;31m'
 yellow='\e[0;33m'
 orange='\e[38;5;166m'
+rt="500"
+#Current Version
+vers="2.2"
+
+# Set Default Data directory
+defdir="/usr/local/share/Eternal_Scanner"
 
 # Set default Scanner Speed
 rt="500"
 
 # Set Default Port
 port="445"
-
-#Current Version
-vers="2.1"
-
-# Set Default Data directory
-defdir="/usr/local/share/Eternal_Scanner"
 
 # Files copied in instalation
 fls="0"
@@ -36,6 +36,8 @@ vuln="vuln.txt"
 vulnos="vuln_OS.txt"
 vulndp="vuln_DP.txt"
 vulntmp="vulntmp.txt"
+vulner="vulner.txt"
+vulnertmp="vulner_tmp.txt"
 vulndptmp="vulndptmp.txt"
 msflog="msflog.log"
 temp1="temp1.txt"
@@ -43,8 +45,22 @@ vuln1="vuln1.txt"
 vulnch="vulnch.txt"
 vulnostmp="vulnostmp.txt"
 temp="temp.txt"
+eromance="python $defdir/check"
 ip=""
+vm="0"
+massd="0"
+var2="0"
 # ------------------------------------------------------------------
+
+# CTRL+C Interrupt for scanner
+trap ctrl_c INT
+function ctrl_c() {
+if [ "$stat" == "1" ]
+then
+pkill -f masscan* >/dev/null 2>&1
+fi
+}
+
 
 #Check install
 if [ ! -d "$defdir" ] 
@@ -63,11 +79,36 @@ if [ -f "$path/$vulnos" ]
 then
 mv "$path/$vulnos" "$defdir/" >/dev/null 2>&1
 fi
+fi
+if [ ! -f "$defdir/mysmb.py" ]
+then
+if [ -f "$path/mysmb.py" ]
+then
+cp "$path/mysmb.py" "$defdir/mysmb.py" >/dev/null 2>&1
+chmod +x $defdir/mysmb.py >/dev/null 2>&1
+fi
+fi
+if [ ! -f "$defdir/mysmb.pyc" ]
+then
+if [ -f "$path/mysmb.pyc" ]
+then
+cp "$path/mysmb.pyc" "$defdir/mysmb.pyc" >/dev/null 2>&1
+chmod +x $defdir/mysmb.pyc >/dev/null 2>&1
+fi
+fi
+if [ ! -f "$defdir/check" ]
+then
+if [ -f "$path/check" ]
+then
+cp "$path/check" "$defdir/check" >/dev/null 2>&1
+chmod +x $defdir/check >/dev/null 2>&1
+fi
 echo -e "$orange" "Updated : Eternal Scanner $vers"
 echo ""
 if [ $fls == "1" ]
 then
-echo -e "$green" "Your Eternal Scanner Data Files were moved to $defdir"
+echo -e "$green" "Your Eternal Scanner Data Files were moved to :"
+echo -e "$yellow""$defdir"
 echo -e ""
 echo -e "$yellow" "Press ENTER key To Continue"
 read -r cont
@@ -77,7 +118,7 @@ cp elog /usr/local/sbin/ >/dev/null 2>&1
 echo ""
 echo -e "$green" "Eternal Scanner was installed in your system"
 echo ""
-echo -e "$orange" "From now on , write (escan) or (escan -h) anywhere to run it."
+echo -e "$orange" "Write (escan) or (escan -h) anywhere to run it."
 echo ""
 echo -e "$yellow" "Press ENTER key To Continue"
 read -r cont
@@ -87,23 +128,122 @@ cp elog /usr/local/sbin/ >/dev/null 2>&1
 echo ""
 echo -e "$green" "Eternal Scanner was installed in your system"
 echo ""
-echo -e "$orange" "From now on , write (escan) or (escan -h) anywhere to run it."
+echo -e "$orange" "Write (escan) or (escan -h) anywhere to run it."
 echo ""
 echo -e "$yellow" "Press ENTER key To Continue"
 read -r cont
 fi
 fi
 
-# CTRL+C Interrupt for scanner
-trap ctrl_c INT
-function ctrl_c() {
-if [ "$stat" == "0" ]
+warn() {
+if [[ $i -gt $wrn ]]
 then
-clear
+wrn=$((wrn+20))
+else
+if [[ $i == "$wrn" ]]
+then
+echo ""
+echo -e "$red""Press CTRL+Z To Stop The IP Check"
+echo ""
+fi
+fi
+}
+
+
+chker() {
+rm -rf $defdir/$temp1
+$eromance $var > $defdir/$temp1 2>&1
+
+# ip file to be created in current path with vulnerable ips
+ipl=$defdir/$vulner
+# Check from output if connection to ip had a timeout
+gtdata=$(cat $defdir/$temp1 | grep "timeout")
+if [[ ! -z $gtdata ]]
+then
+echo -e "$yellow Time Out / Offline"
+else
+gtdata=$(cat $defdir/$temp1 | grep "not patched")
+# timeout was not recieved , so check if ip is vulnerable
+if [[ ! -z $gtdata ]]
+then
+gos=$(cat $defdir/$temp1 | grep "Windows" | awk '{$1=$2=""; print $0}')
+echo -e "$green Vulnerable"
+if [[ -f $defdir/$vulner ]]
+then
+echo "$var | $gos" >> $ipl
+else
+echo "Vulnerable Ips to Eternal Romance Exploit (SMB V1)(MS17-010) - Scanned by Eternal Scanner" > $ipl
+echo "-----------------------------------------------------------------------------------------" >> $ipl
+echo "$var | $gos" >> $ipl
+fi
+else
+echo -e "$yellow Not Vulnerable"
+fi
+fi
+warn
+}
+
+etr() {
+wrn="0"
+f1="$defdir/check"
+f2="$defdir/mysmb.py"
+f3="$defdir/mysmb.pyc"
+if [ ! -f "$f1" ]
+then
+echo -e "$yellow""An Important dependency is missing ($cyan check$yellow file)"
+echo -e "$green""Write (escan -u) to update Eternal Scanner"
 exit 1
-elif [ "$stat" == "1" ]
+fi
+if [ ! -f "$f2" ]
 then
-pkill -f masscan* >/dev/null 2>&1
+echo -e "$yellow""An Important dependency is missing ($cyan mysmb.py$yellow file)"
+echo -e "$green""Write (escan -u) to update Eternal Scanner"
+exit 1
+fi
+if [ ! -f "$f3" ]
+then
+echo -e "$yellow""An Important dependency is missing ($cyan mysmb.pyc$yellow file)"
+echo -e "$green""Write (escan -u) to update Eternal Scanner"
+exit 1
+fi
+if [ -f "$defdir/$vuln" ]
+then
+delf
+tempf=$(tail -n+3 $defdir/$vuln | sed -e "s/:445//g")
+echo "$tempf" > "$defdir/$vulnertmp"
+tr " " "\n" <$defdir/$vulnertmp >$defdir/$vulner
+rm -f "$defdir/$vulnertmp" >/dev/null 2>&1
+mv $defdir/$vulner $defdir/$vulnertmp >/dev/null 2>&1
+lm=$(cat $defdir/$vulnertmp | wc -l)
+$eromance > $defdir/$temp1 2>&1
+chker=$(cat $defdir/$temp1 | grep "ImportError" | awk '{print$5}')
+if [[ ! -z "$chker" ]]
+then
+echo -e "$yellow" "Dependency Missing : $chker"
+echo ""
+echo -e "$green" "Try : apt-get install python-crypto python-impacket python-pyasn1-modules"
+exit 1
+else
+echo -e "$green" "Eternal Romance (SMB V1) IP List Check"
+echo -e "$cyan" "Checking :$yellow $defdir/$vuln"
+echo -e "$orange""*****************************************************"
+echo -e "$cyan""Output file:$green $defdir/$vulner"
+echo -e "$orange""*****************************************************"
+echo ""
+echo -e "$red""Press CTRL+Z To Stop The IP Check"
+echo ""
+for i in $(seq "$lm")
+do
+lg=$defdir/erlog.txt
+rm $lg >/dev/null 2>&1
+var=$(cat $defdir/$vulnertmp | awk -v nb=$i 'NR==nb')
+echo -ne "$cyan""IP$yellow $i$cyan from$yellow $lm$cyan :$green $var$cyan --> "
+chker
+done 
+fi
+else
+echo -e "$yellow" "Vulnerable Ip file was not yet created"
+exit 1
 fi
 }
 
@@ -148,17 +288,37 @@ else
 echo ""
 echo -e "$yellow""Search results for : $green $srch"
 echo -e "$orange""*****************************************************$green"
+echo -e "$orange""***************$cyan Eternal Blue Results$orange ****************"
+echo -e "$orange""*****************************************************$green"
 var=$(cat "$defdir/$vulnos" | grep "$srch" | sed -e "s/:445//g")
 lc=$(cat "$defdir/$vulnos" | grep "$srch" | sed -e "s/:445//g" | wc -l)
+
+if [[ -f $defdir/$vulner ]]
+then
+var1=$(cat "$defdir/$vulner" | grep "$srch")
+lc1=$(cat "$defdir/$vulner" | grep "$srch" | wc -l)
+fi
+
 if [[ -z "$var" ]]
 then
 echo -e "$yellow" "No results found with search term : $srch"
 else
 cat "$defdir/$vulnos" | grep "$srch" | sed -e "s/:445//g"
-fi
 echo -e "$orange""*****************************************************"
-echo -e "$cyan" "Found :$yellow $lc$cyan Results"
+echo -e "$cyan" "Found :$yellow $lc$cyan Eternal Blue Results"
+echo -e "$green"""
+fi
+
+if [[ ! -z $var1 ]]
+then
+echo -e "$orange""*****************************************************"
+echo -e "$orange""*************$cyan Eternal Romance Results$orange ***************"
+echo -e "$orange""*****************************************************$green"
+cat "$defdir/$vulner" | grep "$srch"
+echo -e "$orange""*****************************************************"
+echo -e "$cyan" "Found :$yellow $lc1$cyan Eternal Romance Results"
 echo -e "$green" ""
+fi
 read -p "Press [Enter] key to Return"
 schos
 fi
@@ -176,6 +336,8 @@ rm -f "$defdir/msflog.log" >/dev/null 2>&1
 rm -f "$path/paused.conf" >/dev/null 2>&1
 rm -f "$defdir/pid.tmp" >/dev/null 2>&1
 rm -f "$defdir/x$i" >/dev/null 2>&1
+rm -f "$defdir/$vulnertmp" >/dev/null 2>&1
+rm -f "$defdir/stat" >/dev/null 2>&1
 }
 
 # Eternal Scanner Logo
@@ -221,21 +383,21 @@ exit 1
 fi 
 
 # Python checks for Eternal Romance Vulnerability check to be implemented
-#which python > /dev/null 2>&1
-#      if [ "$?" -eq "1" ]; then
-#   echo -e "$red" "Python Missing"
-#echo ""
-#echo -e "$yellow" "Try : apt-get install python"
-#exit 1
-#fi 
+which python > /dev/null 2>&1
+      if [ "$?" -eq "1" ]; then
+   echo -e "$red" "Python Missing"
+echo ""
+echo -e "$yellow" "Try : apt-get install python"
+exit 1
+fi 
 
-#which pip > /dev/null 2>&1
-#      if [ "$?" -eq "1" ]; then
-#   echo -e "$red" "Pip Missing"
-#echo ""
-#echo -e "$yellow" "Try : apt-get install python-pip"
-#exit 1
-#fi 
+which pip > /dev/null 2>&1
+      if [ "$?" -eq "1" ]; then
+   echo -e "$red" "Pip Missing"
+echo ""
+echo -e "$yellow" "Try : apt-get install python-pip"
+exit 1
+fi 
 }
 
 # Function to extract data from metasploit results 
@@ -362,14 +524,15 @@ echo -e "$yellow" "----------------------------"
 cat "$defdir/x$i"
 echo -e "$yellow" "----------------------------"
 echo ""
-echo -e "$green" "Press CTRL-C (1X ONLY) to stop vulnerability check on task $i"
+echo -e "$green" "Press CTRL+C (1X ONLY) to stop vulnerability check on task $i"
 echo -e "$green" "(aborting this process now will not verify all ips in task $i of $tms)"
 echo ""
 echo -e "\033[33;7mPlease Wait , checking $lc ips from task $i of $tms may take a while\033[0m"
 stat="2"
 
 # Execute msfconsole script , get PID from msfconsole and start elog
-
+rm -rf "$defdir/stat" >/dev/null 2>&1
+echo "2" > $defdir/stat 
 msfconsole -r $defdir/msf.rc >/dev/null 2>&1 & echo $! > $defdir/pid.tmp & elog
 sleep 2
 getdata
@@ -394,11 +557,13 @@ echo "set threads $thr" >> "$defdir/msf.rc"
 echo "exploit" >> "$defdir/msf.rc"
 echo "quit -y" >> "$defdir/msf.rc"
 echo ""
-echo -e "$green" "Press CTRL-C (1X ONLY) to stop ips vulnerability check"
+echo -e "$green" "Press CTRL+C (1X ONLY) to stop ips vulnerability check"
 echo -e "$green" "(aborting this process will not verify all ips)"
 echo ""
 echo -e "\033[33;7mPlease Wait , checking $lc ips may take a while\033[0m"
 stat="2"
+rm -rf "$defdir/stat" >/dev/null 2>&1
+echo "2" > $defdir/stat
 msfconsole -r $defdir/msf.rc >/dev/null 2>&1 & echo $! > $defdir/pid.tmp & elog
 sleep 2
 getdata
@@ -406,26 +571,16 @@ getdata
 
 # Function to split ip list file bigger than 500 ips
 splitip(){
-split -a 5 -d -l 500 $defdir/msfip $defdir/x
+split -d -l 500 $defdir/msfip $defdir/x
 tms=$(find $defdir/ -name "x*" | wc -l)
 for i in $(seq 0 "$tms")
 do
 tm=$((i+1))
-if [[ "$tm" -ge 10 && "$tm" -le 99 ]]
+if [ "$tm" == "11" ]
 then
-mv "$defdir/x000$i" "$defdir/x$tm" >/dev/null 2>&1
-fi
-if [[ "$tm" -ge 100 && "$tm" -le 999 ]]
-then
-mv "$defdir/x00$i" "$defdir/x$tm" >/dev/null 2>&1
-fi
-if [[ "$tm" -ge 1000 && "$tm" -le 9999 ]]
-then
+mv "$defdir/x$i" "$defdir/x$tm" >/dev/null 2>&1
+else
 mv "$defdir/x0$i" "$defdir/x$tm" >/dev/null 2>&1
-fi
-if [[ "$tm" -ge 0 && "$tm" -le 9 ]]
-then
-mv "$defdir/x0000$i" "$defdir/x$tm" >/dev/null 2>&1
 fi
 done
 msfm
@@ -478,7 +633,7 @@ fi
 val="0.0.0.0/0"
 if [ "$ip" == "$val" ]
 then
-echo -e "$cyan" "Scanning all internet will take hours to finish"
+echo -e "$cyan" "Scanning all internet will take hours !"
 echo ""
 echo -ne "$green" "Do you still want to continue ? (y/N) : ";tput sgr0
 read -r opt
@@ -489,8 +644,10 @@ echo -e "$green" "Press CTRL-C (1X ONLY) to stop the scanner "
 echo ""
 tn=$(date +"%H:%M:%S")
 echo -e "\033[33;7mScanner started at $tn , Please Wait\033[0m"
+rm -rf "$defdir/stat" >/dev/null 2>&1
 stat="1"
 masscan "$ip" -p "$port" --rate "$rt" --exclude 255.255.255.255 --output-filename "$mass" >/dev/null 2>&1 
+echo ""
 tst=$(date +"%H:%M:%S")
 echo -e "\033[33;7mScanner stopped/finished at $tst \033[0m"
 sleep 4
@@ -507,8 +664,10 @@ echo -e "$green" "Press CTRL-C (1X ONLY) to stop the scanner "
 echo ""
 tn=$(date +"%H:%M:%S")
 echo -e "\033[33;7mScanner started at $tn , Please Wait\033[0m"
+rm -rf "$defdir/stat" >/dev/null 2>&1
 stat="1"
 masscan "$ip" -p "$port" --rate "$rt" --output-filename "$mass" >/dev/null 2>&1 
+echo ""
 tst=$(date +"%H:%M:%S")
 echo -e "\033[33;7mScanner stopped/finished at $tst \033[0m"
 sleep 4
@@ -537,7 +696,8 @@ echo ""
 echo -e "$yellow" "----------------------------"
 lc=$(cat $defdir/msfip | wc -l)
 echo "Collected $lc ips"
-echo -e "$yellow" "Checking if the $lc ips above are vulnerable"
+echo -e "$yellow" "Checking if the $lc ips are vulnerable"
+sleep 4
 
 # If scanner ip list is bigger than 500 ips , then split the msfip list in multiple files with 500 ips each one
 if [ "$lc" -gt "500" ]
@@ -558,16 +718,38 @@ fi
 # escan only written in terminal
 if [ -z "$1" ]
 then
+echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+echo -e "$yellow" "Opps , not connected to Internet"
+exit 1
+fi
 chkdep
 logo
 mass
 exit 1
 fi
 
+if [ "$1" == "-er" ]
+then
+echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+echo -e "$yellow" "Opps , not connected to Internet"
+exit 1
+fi
+chkdep
+logo
+etr
+exit 1
+fi
+
 #Switch for input ip
 if [ "$1" == "-i" ]
 then
-
+echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+echo -e "$yellow" "Opps , not connected to Internet"
+exit 1
+fi
 if [ -z "$2" ]
 then
 escan -h
@@ -613,12 +795,13 @@ if [ "$1" == "-v" ]
 then
 if [ -f "$defdir/$vuln" ]
 then
+logo
 echo -e "$orange" "Displaying Vulnerability IP file"
 echo -e "$yellow" "Currently stored in $defdir"
-echo -e "$cyan" "+---------------------------------------------------------------------------+"
+echo -e "$cyan" "+----------------------------------------------+"
 echo -e "$green" ""
 cat "$defdir/$vuln" | sed -e "s/:445//g"
-echo -e "$cyan" "+---------------------------------------------------------------------------+"
+echo -e "$cyan" "+----------------------------------------------+"
 exit 1
 else
 echo -e "$yellow" "Vulnerability IP file list not yet available"
@@ -631,17 +814,18 @@ if [ "$1" == "-vo" ]
 then
 if [ -f "$defdir/$vulnos" ]
 then
+logo
 echo -e "$orange" "Displaying Detailed OS Vulnerability IP file"
 echo -e "$yellow" "Currently stored in $defdir"
-echo -e "$cyan" "+---------------------------------------------------------------------------+"
+echo -e "$cyan" "+----------------------------------------------+"
 echo -e "$green" ""
 cat "$defdir/$vulnos" | sed -e "s/:445//g"
-echo -e "$cyan" "+---------------------------------------------------------------------------+"
+echo -e "$cyan" "+----------------------------------------------+"
 exit 1
 else
 if [ -f "$defdir/$vuln" ]
 then
-echo -e "$green" "To display this file you must first write (escan -ck) on terminal so your"
+echo -e "$green" "To display this file you must first write (escan -c) on terminal so your"
 echo -e "$green" "vulnerable ip list can be checked , and then you can use (escan -vo)"
 exit 1
 else
@@ -653,6 +837,11 @@ fi
 fi
 if [ "$1" == "-u" ]
 then
+echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+echo -e "$yellow" "Opps , not connected to Internet"
+exit 1
+fi
 # Check if eternal scanner is installed on a system path
 es=$(whereis escan |awk '{print$2}')
 el=$(whereis elog |awk '{print$2}')
@@ -670,6 +859,9 @@ which wget > /dev/null 2>&1
       if [ "$?" -eq "1" ]; then
 apt-get install wget -y > /dev/null 2>&1
 fi
+wget https://raw.githubusercontent.com/peterpt/eternal_scanner/master/check -O $defdir/check > /dev/null 2>&1
+wget https://raw.githubusercontent.com/peterpt/eternal_scanner/master/mysmb.py  -O $defdir/mysmb.py > /dev/null 2>&1
+wget https://raw.githubusercontent.com/peterpt/eternal_scanner/master/mysmb.pyc -O $defdir/mysmb.pyc > /dev/null 2>&1
 wget https://raw.githubusercontent.com/peterpt/eternal_scanner/master/escan -O $es > /dev/null 2>&1
 wget https://raw.githubusercontent.com/peterpt/eternal_scanner/master/elog -O $el > /dev/null 2>&1
 chmod +x $es >/dev/null 2>&1
@@ -702,16 +894,17 @@ echo "----------------------------------------------------"
 echo "Available Switches :"
 echo ""
 echo "escan -i 192.168.1.1/24 (Scan Ip/Ip Range)"
-echo "escan -s  (Scanner speed Min: 100 Max: 10000000 /Default : 500"
+echo "escan -s  (Scanner speed Min: 100 Max: 10000000 /Default : 500)"
 echo "escan -c  (Verify if ips in vuln.txt are still vulnerable & update list)"
 echo "escan -ck /someiplistfile.txt (Will check current user manual ip list)"
+echo "escan -er (Verify if ips in vuln.txt are vulnerable to Eternal Romance Vulnerability)"
 echo "escan -l  (To search in database)"
 echo "escan -v  (Display current vulnerable ip list on screen)"
 echo "escan -vo (Display current vulnerable detailed OS ip list on screen)"
 echo "escan -u  (Update Eternal Scanner binaries from github)"
 echo "escan -h  (This screen)"
 echo ""
-echo "Example : escan -i 192.68.1.1/24 -s 3000 (for 3000 packets /s)"
+echo "Example : escan -i 192.168.1.1/24 -s 3000 (for 3000 packets /s)"
 echo ""
 exit 1
 fi
@@ -720,6 +913,11 @@ out="$2"
 
 if [ "$1" == "-c" ]
 then
+echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+echo -e "$yellow" "Opps , not connected to Internet"
+exit 1
+fi
 if [ -f "$defdir/$vuln" ]
 then
 delf
@@ -733,7 +931,7 @@ tempf=$(tail -n+3 $defdir/$vuln | sed -e "s/:445//g")
 echo "$tempf" > "$defdir/$vulntmp"
 tr " " "\n" <$defdir/$vulntmp >$msfi
 rm -f "$defdir/$vulntmp" >/dev/null 2>&1
-lm=$(cat "$msfi" | wc -l)
+lm=$(cat $defdir/$msfi | wc -l)
 rm -f "$defdir/$vuln" >/dev/null 2>&1
 if [ "$lm" -gt "500" ]
 then
@@ -754,6 +952,11 @@ fi
 
 if [ "$1" == "-ck" ]
 then
+echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+echo -e "$yellow" "Opps , not connected to Internet"
+exit 1
+fi
 if [ -z "$out" ]
 then
 echo "No input iplist file to check."
@@ -785,6 +988,11 @@ fi
 fi
 if [ "$1" == "-s" ]
 then
+echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+echo -e "$yellow" "Opps , not connected to Internet"
+exit 1
+fi
 if [ -z "$out" ]
 then
 echo "Invalid argument , write ./escan -h for help"
